
import { Inter } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
import ThemeSwitcher from "./themeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

 
  return (
    <html lang="en">
      <body>
        <header>
          <Image src="/images/icon-accessibility.svg" alt="topic icon" width={40} height={40}/>
          <h1>Accessibility</h1>
          <ThemeSwitcher/>
        </header>
        {children}
        </body>
    </html>
  );
}
